CREATE
    TABLE
        customer(
            customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            email VARCHAR(255) NOT NULL,
            full_name VARCHAR(255) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            CONSTRAINT pk_customer PRIMARY KEY(customer_id)
        );

CREATE
    TABLE
        product(
            product_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(255) NOT NULL,
            description TEXT,
            price DECIMAL(
                10,
                2
            ) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            CONSTRAINT pk_product PRIMARY KEY(product_id)
        );

CREATE
    TABLE
        category(
            category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(100) NOT NULL,
            CONSTRAINT pk_category PRIMARY KEY(category_id)
        );

CREATE
    TABLE
        product_category(
            product_id BIGINT NOT NULL,
            category_id BIGINT NOT NULL,
            CONSTRAINT pk_product_category PRIMARY KEY(
                product_id,
                category_id
            ),
            CONSTRAINT fk_product_category_product_id FOREIGN KEY(product_id) REFERENCES product(product_id),
            CONSTRAINT fk_product_category_category_id FOREIGN KEY(category_id) REFERENCES category(category_id)
        );

CREATE
    TABLE
        customer_order(
            customer_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            customer_id BIGINT NOT NULL,
            order_date TIMESTAMP NOT NULL DEFAULT NOW(),
            total_amount DECIMAL(
                10,
                2
            ) NOT NULL,
            CONSTRAINT pk_customer_order PRIMARY KEY(customer_order_id),
            CONSTRAINT fk_customer_order_customer_id FOREIGN KEY(customer_id) REFERENCES customer(customer_id)
        );

CREATE
    TABLE
        order_item(
            order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            customer_order_id BIGINT NOT NULL,
            product_id BIGINT NOT NULL,
            quantity INTEGER NOT NULL,
            unit_price DECIMAL(
                10,
                2
            ) NOT NULL,
            CONSTRAINT pk_order_item PRIMARY KEY(order_item_id),
            CONSTRAINT fk_order_item_customer_order_id FOREIGN KEY(customer_order_id) REFERENCES customer_order(customer_order_id),
            CONSTRAINT fk_order_item_product_id FOREIGN KEY(product_id) REFERENCES product(product_id)
        );
